import React, { useEffect, useRef } from "react";
import { useRequestStore } from "../mstore/mRequestStore";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; 

const MProReqToday = () => {
  const { processedRequests = [], fetchAllProcessedRequests, loading, error } =
    useRequestStore();
  const containerRef = useRef();

  useEffect(() => {
    fetchAllProcessedRequests("all");
  }, [fetchAllProcessedRequests]);

  const handleDownloadTodayPDF = () => {
    if (!containerRef.current) return;

    const pdf = new jsPDF({ orientation: "portrait", unit: "px", format: "a4" });
    const today = new Date();
    const todayStr = today.toISOString().split("T")[0];
    const formattedDate = today.toLocaleDateString();
    const formattedTime = today.toLocaleTimeString();

    const todayRequests = processedRequests.filter((r) => {
      if (!r.processedAt) return false;
      return new Date(r.processedAt).toISOString().split("T")[0] === todayStr;
    });
    

    // Header 
    pdf.setFontSize(18);
    pdf.text("JW-Sudio - Daily Rental Requests Report", 40, 40);
    pdf.setFontSize(12);
    pdf.text(`Date: ${formattedDate}`, 40, 60);
    pdf.text(`Generated at: ${formattedTime}`, 40, 75);

    // Summary 
    const accepted = todayRequests.filter((r) => r.status === "accept");
    const rejected = todayRequests.filter((r) => r.status === "reject");
    const totalIncome = accepted.reduce((sum, r) => sum + (r.amount || 0), 0);
    const avgDeposit = accepted.length ? totalIncome / accepted.length : 0;

    const summaryY = 95;
    pdf.setFontSize(13);
    pdf.text("Summary", 40, summaryY);

    pdf.setFontSize(11);
    pdf.text(`Total Requests: ${todayRequests.length}`, 40, summaryY + 20);
    pdf.text(`Accepted Requests: ${accepted.length}`, 40, summaryY + 35);
    pdf.text(`Rejected Requests: ${rejected.length}`, 40, summaryY + 50);
    pdf.text(`Total Income (Accepted): Rs. ${totalIncome.toFixed(2)}`, 40, summaryY + 65);
    pdf.text(`Average Deposit: Rs. ${avgDeposit.toFixed(2)}`, 40, summaryY + 80);

    //  Table 
    const tableData = todayRequests.map((req) => [
      Array.isArray(req.items)
        ? req.items.map((i) => i.name).join(", ")
        : req.items || "-",
      `Rs. ${req.amount ?? "-"}`,
      req.email ?? "-",
      req.status === "accept" ? "Accepted" : "Rejected",
      req.processedAt ? new Date(req.processedAt).toLocaleString() : "-",
    ]);

    console.log("autoTable exists?", typeof autoTable); // debug check

    autoTable(pdf, {
      startY: summaryY + 100,
      head: [["Items", "Amount", "Email", "Status", "Processed At"]],
      body: tableData,
      styles: { fontSize: 10, cellPadding: 4 },
      headStyles: { fillColor: [0, 51, 170], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    // set Footer
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFontSize(10);
    pdf.text(
      "Generated by JW-Studio Admin System | Confidential Report",
      40,
      pageHeight - 20
    );

    pdf.save(`Daily_Rental_Requests_${todayStr}.pdf`);
  };

  if (loading) return <p>Loading processed requests...</p>;
  if (error) return <p className="text-red-600">{error}</p>;

  // get date-time
  const todayStr = new Date().toISOString().split("T")[0];
  const todayRequests = processedRequests.filter((r) => {
    if (!r.processedAt) return false;
    return new Date(r.processedAt).toISOString().split("T")[0] === todayStr;
  });

  return (
    <div className="bg-white shadow-md rounded-xl p-6 w-full">
      <h1 className="text-2xl font-semibold text-slate-800 mb-6 text-center">
        Processed Requests of Today
      </h1>

      <div ref={containerRef} className="overflow-x-auto">
        <table className="min-w-full text-left text-sm border">
          <thead className="bg-gray-100">
            <tr>
              <th className="py-2 px-4 border">Items</th>
              <th className="py-2 px-4 border">Amount</th>
              <th className="py-2 px-4 border">Email</th>
              <th className="py-2 px-4 border">Status</th>
              <th className="py-2 px-4 border">Processed At</th>
            </tr>
          </thead>
          <tbody>
            {todayRequests.length === 0 ? (
              <tr>
                <td className="py-2 px-4 border" colSpan={5}>
                  No processed requests today.
                </td>
              </tr>
            ) : (
              todayRequests.map((req) => ( 
                <tr key={req._id}>
                  <td className="py-2 px-4 border">
                    {Array.isArray(req.items)
                      ? req.items.map((i) => i.name).join(", ")
                      : req.items}
                  </td>
                  <td className="py-2 px-4 border">{req.amount ?? "-"}</td>
                  <td className="py-2 px-4 border">{req.email ?? "-"}</td>
                  <td
                    className={`py-2 px-4 border font-semibold ${
                      req.status === "accept"
                        ? "text-green-600"
                        : "text-red-600"
                    }`}
                  >
                    {req.status ?? "-"}
                  </td>
                  <td className="py-2 px-4 border">
                    {req.processedAt
                      ? new Date(req.processedAt).toLocaleString()
                      : "-"}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {todayRequests.length > 0 && (
        <div className="text-center mt-6">
          <button
            onClick={handleDownloadTodayPDF}
            className="bg-blue-600 text-white px-5 py-2 rounded hover:bg-blue-700"
          >
            Download Daily Report
          </button>
        </div>
      )}
    </div>
  );
};

export default MProReqToday;

